TYPE=VIEW
query=select sum(`vt_ptr`.`tb_hour_production`.`target`) AS `target`,sum(`vt_ptr`.`tb_hour_production`.`actual`) AS `actual`,`vt_ptr`.`tb_hour_production`.`floor` AS `floor`,`vt_ptr`.`tb_hour_production`.`unit` AS `unit`,`vt_ptr`.`tb_hour_production`.`date` AS `date` from `vt_ptr`.`tb_hour_production` where (`vt_ptr`.`tb_hour_production`.`target` <> 0) group by `vt_ptr`.`tb_hour_production`.`floor`,`vt_ptr`.`tb_hour_production`.`unit`,`vt_ptr`.`tb_hour_production`.`date` order by `vt_ptr`.`tb_hour_production`.`date`
md5=e51291380a3363e4dec019f3b195e48f
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2014-08-28 04:01:01
create-version=1
source=SELECT sum( `target` ) AS \'target\', sum(actual) as actual, floor, unit, date FROM \n`tb_hour_production` WHERE target != 0 GROUP BY floor, unit, date ORDER BY `date` ASC
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select sum(`vt_ptr`.`tb_hour_production`.`target`) AS `target`,sum(`vt_ptr`.`tb_hour_production`.`actual`) AS `actual`,`vt_ptr`.`tb_hour_production`.`floor` AS `floor`,`vt_ptr`.`tb_hour_production`.`unit` AS `unit`,`vt_ptr`.`tb_hour_production`.`date` AS `date` from `vt_ptr`.`tb_hour_production` where (`vt_ptr`.`tb_hour_production`.`target` <> 0) group by `vt_ptr`.`tb_hour_production`.`floor`,`vt_ptr`.`tb_hour_production`.`unit`,`vt_ptr`.`tb_hour_production`.`date` order by `vt_ptr`.`tb_hour_production`.`date`
